# Fichier de paramètres pour la connection à la database
# et l'url du site
# inscrire ses paramètres de connection et son url
dbConnect:
    host: #localhost
    dbname: #Blog
    loginDB: #root
    passDB: #root
url: #http://localhost/Projet4/Projet-4-Creez-un-blog-pour-un-ecrivain/
